// This file is generated by Sapper — do not edit it!
import root from "../routes/_layout.html";
import error from "../routes/_error.html";

const d = decodeURIComponent;

const index = {
	js: () => import(/* webpackChunkName: "index" */ "../routes/index.html"),
	css: "__SAPPER_CSS_PLACEHOLDER:index.html__"
};
const guide = {
	js: () => import(/* webpackChunkName: "guide" */ "../routes/guide/index.html"),
	css: "__SAPPER_CSS_PLACEHOLDER:guide/index.html__"
};
const blog = {
	js: () => import(/* webpackChunkName: "blog" */ "../routes/blog/index.html"),
	css: "__SAPPER_CSS_PLACEHOLDER:blog/index.html__"
};
const blog_$slug = {
	js: () => import(/* webpackChunkName: "blog_$slug" */ "../routes/blog/[slug].html"),
	css: "__SAPPER_CSS_PLACEHOLDER:blog/[slug].html__"
};
const repl = {
	js: () => import(/* webpackChunkName: "repl" */ "../routes/repl/index.html"),
	css: "__SAPPER_CSS_PLACEHOLDER:repl/index.html__"
};

export const manifest = {
	ignore: [/^\/blog\/rss.xml$/, /^\/gist\/create$/, /^\/gist\/([^\/]+?)$/, /^\/api\/examples\/([^\/]+?)$/, /^\/api\/guide$/, /^\/api\/guide\/contents$/, /^\/api\/guide\/demo\/([^\/]+?)$/, /^\/api\/blog$/, /^\/api\/blog\/([^\/]+?)$/],

	pages: [
		{
			// index.html
			pattern: /^\/?$/,
			parts: [
				{ component: index }
			]
		},

		{
			// guide/index.html
			pattern: /^\/guide\/?$/,
			parts: [
				null,
				{ component: guide }
			]
		},

		{
			// blog/index.html
			pattern: /^\/blog\/?$/,
			parts: [
				null,
				{ component: blog }
			]
		},

		{
			// blog/[slug].html
			pattern: /^\/blog\/([^\/]+?)\/?$/,
			parts: [
				null,
				{ component: blog_$slug, params: match => ({ slug: d(match[1]) }) }
			]
		},

		{
			// repl/index.html
			pattern: /^\/repl\/?$/,
			parts: [
				null,
				{ component: repl }
			]
		}
	],

	root,

	error
};

// this is included for legacy reasons
export const routes = {};

import("/Users/208311/Development/SVELTE/svelte.technology/node_modules/sapper/sapper-dev-client.js").then(client => {
	client.connect(10000);
});