// This file is generated by Sapper — do not edit it!
export const timestamp = 1537756541015;

export const files = [
	"curl.js",
	"favicon.ico",
	"favicon.png",
	"fonts/Inconsolata/Inconsolata-Bold.woff",
	"fonts/Inconsolata/Inconsolata-Bold.woff2",
	"fonts/Inconsolata/Inconsolata-Regular.woff",
	"fonts/Inconsolata/Inconsolata-Regular.woff2",
	"fonts/Inconsolata/OFL.txt",
	"fonts/Rajdhani/Rajdhani-Bold.woff",
	"fonts/Rajdhani/Rajdhani-Bold.woff2",
	"fonts/Rajdhani/Rajdhani-Medium.woff",
	"fonts/Rajdhani/Rajdhani-Medium.woff2",
	"fonts/Rajdhani/Rajdhani-Regular.woff",
	"fonts/Rajdhani/Rajdhani-Regular.woff2",
	"fonts/Roboto/Roboto-Bold.woff",
	"fonts/Roboto/Roboto-Bold.woff2",
	"fonts/Roboto/Roboto-Light.woff",
	"fonts/Roboto/Roboto-Light.woff2",
	"fonts/Roboto/Roboto-LightItalic.woff",
	"fonts/Roboto/Roboto-LightItalic.woff2",
	"icons/check.svg",
	"icons/collapse.svg",
	"icons/download.svg",
	"icons/dropdown.svg",
	"icons/expand.svg",
	"icons/flip.svg",
	"icons/fork.svg",
	"icons/link.svg",
	"icons/save.svg",
	"images/twitter-card.png",
	"manifest.json",
	"repl-viewer.css",
	"svelte-app.json",
	"svelte-logo-192.png",
	"svelte-logo-512.png"
];
export { files as assets }; // legacy

export const shell = [
	"client/f68b51b6b4627c0055fe/main.js",
	"client/b138fe4e9b98d660e6b3.worker.js",
	"client/svelte.b138fe4e9b98d660e6b3.worker.js",
	"client/f68b51b6b4627c0055fe/blog.blog.js",
	"client/f68b51b6b4627c0055fe/blog_$slug.blog_$slug.js",
	"client/f68b51b6b4627c0055fe/codemirror.codemirror.js",
	"client/f68b51b6b4627c0055fe/guide.guide.js",
	"client/f68b51b6b4627c0055fe/index.index.js",
	"client/rollup.b138fe4e9b98d660e6b3.worker.js",
	"client/f68b51b6b4627c0055fe/0.0.js",
	"client/f68b51b6b4627c0055fe/1.1.js",
	"client/f68b51b6b4627c0055fe/2.2.js",
	"client/f68b51b6b4627c0055fe/3.3.js",
	"client/f68b51b6b4627c0055fe/repl.repl.js",
	"client/f68b51b6b4627c0055fe/vendors~codemirror.vendors~codemirror.js",
	"client/f68b51b6b4627c0055fe/vendors~repl.vendors~repl.js"
];

export const routes = [
	{ pattern: /^\/?$/ },
	{ pattern: /^\/guide\/?$/ },
	{ pattern: /^\/blog\/?$/ },
	{ pattern: /^\/blog\/([^\/]+?)\/?$/ },
	{ pattern: /^\/repl\/?$/ }
];