// This file is generated by Sapper — do not edit it!
import * as route_blog_rss_xml from "../routes/blog/rss.xml.js";
import * as route_gist_create from "../routes/gist/create.js";
import * as route_gist_$id from "../routes/gist/[id].js";
import * as route_api_examples_$slug from "../routes/api/examples/[slug].js";
import * as route_api_guide from "../routes/api/guide/index.js";
import * as route_api_guide_contents from "../routes/api/guide/contents.js";
import * as route_api_guide_demo_$hash from "../routes/api/guide/demo/[hash].js";
import * as route_api_blog from "../routes/api/blog/index.js";
import * as route_api_blog_$slug from "../routes/api/blog/[slug].js";
import index from "../routes/index.html";
import guide from "../routes/guide/index.html";
import blog from "../routes/blog/index.html";
import blog_$slug from "../routes/blog/[slug].html";
import repl from "../routes/repl/index.html";
import root from "../routes/_layout.html";
import error from "../routes/_error.html";

const d = decodeURIComponent;

export const manifest = {
	server_routes: [
		{
			// blog/rss.xml.js
			pattern: /^\/blog\/rss.xml$/,
			handlers: route_blog_rss_xml,
			params: () => ({})
		},

		{
			// gist/create.js
			pattern: /^\/gist\/create$/,
			handlers: route_gist_create,
			params: () => ({})
		},

		{
			// gist/[id].js
			pattern: /^\/gist\/([^\/]+?)$/,
			handlers: route_gist_$id,
			params: match => ({ id: d(match[1]) })
		},

		{
			// api/examples/[slug].js
			pattern: /^\/api\/examples\/([^\/]+?)$/,
			handlers: route_api_examples_$slug,
			params: match => ({ slug: d(match[1]) })
		},

		{
			// api/guide/index.js
			pattern: /^\/api\/guide$/,
			handlers: route_api_guide,
			params: () => ({})
		},

		{
			// api/guide/contents.js
			pattern: /^\/api\/guide\/contents$/,
			handlers: route_api_guide_contents,
			params: () => ({})
		},

		{
			// api/guide/demo/[hash].js
			pattern: /^\/api\/guide\/demo\/([^\/]+?)$/,
			handlers: route_api_guide_demo_$hash,
			params: match => ({ hash: d(match[1]) })
		},

		{
			// api/blog/index.js
			pattern: /^\/api\/blog$/,
			handlers: route_api_blog,
			params: () => ({})
		},

		{
			// api/blog/[slug].js
			pattern: /^\/api\/blog\/([^\/]+?)$/,
			handlers: route_api_blog_$slug,
			params: match => ({ slug: d(match[1]) })
		}
	],

	pages: [
		{
			// index.html
			pattern: /^\/?$/,
			parts: [
				{ name: "index", file: "index.html", component: index }
			]
		},

		{
			// guide/index.html
			pattern: /^\/guide\/?$/,
			parts: [
				null,
				{ name: "guide", file: "guide/index.html", component: guide }
			]
		},

		{
			// blog/index.html
			pattern: /^\/blog\/?$/,
			parts: [
				null,
				{ name: "blog", file: "blog/index.html", component: blog }
			]
		},

		{
			// blog/[slug].html
			pattern: /^\/blog\/([^\/]+?)\/?$/,
			parts: [
				null,
				{ name: "blog_$slug", file: "blog/[slug].html", component: blog_$slug, params: match => ({ slug: d(match[1]) }) }
			]
		},

		{
			// repl/index.html
			pattern: /^\/repl\/?$/,
			parts: [
				null,
				{ name: "repl", file: "repl/index.html", component: repl }
			]
		}
	],

	root,

	error
};

// this is included for legacy reasons
export const routes = {};