const cache = {};

function get(url) {
	return new Promise((fulfil, reject) => {
		const request = new XMLHttpRequest();
		request.open('GET', url);
		request.onload = () => fulfil( request );
		request.onerror = () => reject( new TypeError('Network request failed') );
		request.send();
	});
}

function post(url, data) {
	return new Promise((fulfil, reject) => {
		const request = new XMLHttpRequest();
		request.open('POST', url);
		request.onload = () => fulfil(request);
		request.onerror = () => reject(new TypeError('Network request failed'));
		request.send(data);
	});
}

// https://api.github.com

export function getComponentFromGist ( id ) {
	let cancelled = false;

	if ( !cache[ id ] ) {
		cache[ id ] = get(`/gists/${id}`)
			.catch( () => get(`/gists/${id}`))
			.then( r => JSON.parse(r.responseText) )
			.then( gist => {
				const components = [];

				const componentFiles = Object.keys( gist.files ).filter( file => /\.html$/.test( file ) );

				if ( componentFiles.length === 1 && componentFiles[0] === 'component.html' ) {
					// legacy
					components.push({
						name: 'App',
						entry: true,
						source: gist.files[ 'component.html' ].content
					});
				} else {
					componentFiles.forEach( file => {
						const name = file.slice( 0, -5 );
						const source = gist.files[ file ].content;

						components.push({ name, entry: name === 'App', source });
					});
				}

				const jsonFile = gist.files[ 'data.json' ];
				const json = jsonFile && jsonFile.content || '{}';

				return { components, json };
			})
			.catch( err => {
				cache[ id ] = null;
				throw err;
			});
	}

	const promise = cache[ id ].then( component => {
		if ( cancelled ) throw new Error( `Request was cancelled` );
		return component;
	});

	promise.cancel = () => {
		cancelled = true;
	};

	return promise;
}

export function saveComponentAsGist ( components, json ) {
	const files = {
		'README.md': {
			content: `# Svelte component\n\nThis gist was generated by the [Svelte REPL](https://svelte.technology/repl). Visit https://svelte.technology/repl?gist=this_gist_id to see it.`
		},

		'data.json': {
			content: json
		}
	};

	components.forEach( component => {
		files[ `${component.name}.html` ] = {
			content: component.source
		};
	});

	const body = JSON.stringify({
		description: 'Svelte component',
		public: true,
		files
	});

	return post(`/gists`, body)
		.catch(() => post(`/gists`, body))
		.then(r => JSON.parse(r.responseText))
		.then(gist => gist.id);
}

// https://api.github.com